spring.application.name=backend-venta
spring.datasource.url=jdbc:postgresql://localhost:5432/ventas
spring.datasource.username=postgres
spring.datasource.password=Templete1212
# Driver (Spring Boot lo detecta, pero se recomienda dejarlo explícito)
spring.datasource.driver-class-name=org.postgresql.Driver
# JPA/Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
springdoc.api-docs.enabled=true
springdoc.api-docs.path=/api-docs

springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.path=/swagger-ui

# Incluir mensajes de error en las respuestas
server.error.include-message=always
server.error.include-binding-errors=always

# Mostrar stacktrace solo cuando se pase el parámetro ?trace=true
server.error.include-stacktrace=on_param

# No incluir el nombre de la excepción en la respuesta
server.error.include-exception=false

